apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: myapp
    color: blue  # This will initially point to the blue deployment.
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
